[package]
name = "overcast-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1", default-features = false }
ctrlc = "3.4.2"
overcast-core = { path = "../overcast-core" }
