[package]
name = "overcast-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1", features = ["wayland"] }

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
