name: Rust

on:
  push:
    branches:
      - master

jobs:
  format:
    name: Check Format
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          components: rustfmt
          rust-version: stable
      - name: Build | Format
        run: cargo fmt --check

  lint:
    name: Lint
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          components: clippy
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Lint
        run: cargo clippy

  check:
    name: Check
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Check
        run: cargo check

  build:
    name: Build
    timeout-minutes: 3
    runs-on: ubuntu-latest
    needs:
      - check
      - lint
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Build
        run: cargo build
