name: Rust

on:
  push:
    branches:
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          components: rustfmt
          rust-version: stable
      - name: Build | Format
        run: cargo fmt --check

  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          components: clippy
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Lint
        run: cargo clippy

  check:
    name: Check
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Check
        run: cargo check

  test:
    name: Test
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Test
        run: cargo test

  build:
    name: Build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - check
      - lint
      - test
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup | Alsa
        run: sudo apt install libasound2-dev libudev-dev
      - name: Build | Build
        run: cargo build
      - name: Build | Artifacts
        uses: actions/upload-artifact@v4
        id: artifacts
        with:
          name: bins
          path: |
            target/debug/overcast-client
            target/debug/overcast-server
          if-no-files-found: warn
          retention-days: 10
          compression-level: 6
          overwrite: false
